elasticsearch:
  build: elasticsearch/
  command: elasticsearch -Des.network.host=0.0.0.0


logstash:
  build: logstash/
  links:
    - elasticsearch


kibana:
  build: kibana/

  links:
    - elasticsearch

nginx:
  image: nginx:1.9.6
  ports:
    - "8000:80"
    - "8888:8888"
  links:
    - kibana
    - elasticsearch


  volumes:
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    - ./nginx/htpasswd:/etc/nginx/htpasswd